---
- name: Create SSH Banner 
  hosts: all
  vars:
   my_hostname: "{{hostname}}"
   my_ipaddr: "{{ip_addr}}"

  tasks: 

  - name: Create a blank Banner file if not exists
    file:
     path: /etc/banner
     state: touch
     mode: 644

  - name: Create a Banner File under /etc
    lineinfile:
     path: /etc/banner
     line: "This is a Test system for Shampa"
     insertafter: EOF

  - name: Update sshd.conf to print a banner while ssh login
    lineinfile:
     path: /etc/ssh/sshd_config 
     insertafter: "^#Banner none"
     line: "Banner /etc/banner"
     state: present

  - name: restart the sshd service to take effect
    service:
     name: sshd
     state: restarted
  
  - name: Create a hosts file entry with veriable
    lineinfile:
     path: /etc/hosts
     insertafter: EOF
     line: "{{my_hostname}} {{my_ipaddr}}"

...
